
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once
#include "Props.h"
#include "EventEmitters.h"
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <jsi/jsi.h>

namespace facebook {
namespace react {

JSI_EXPORT extern const char BlurhashViewComponentName[];

/*
 * `ShadowNode` for <BlurhashView> component.
 */
using BlurhashViewShadowNode = ConcreteViewShadowNode<
    BlurhashViewComponentName,
    BlurhashViewProps,
    BlurhashViewEventEmitter>;

} // namespace react
} // namespace facebook